#!/usr/bin/env python3
"""Publish the repository-level documentation into the portal.

The AsciiDoc under docs/ (practice standards, policies, capabilities) is not
attached to any Structurizr workspace, so site-generatr would never render it.
site-generatr runs Asciidoctor in SAFE mode, which blocks include:: directives
that climb out of a workspace's docs directory — so instead this script
compiles each docs/ area into one generated section of the Enterprise
workspace documentation (headings shifted down one level).

The files in docs/ remain the single source of truth; the *.gen.adoc outputs
are build artifacts and are gitignored.

Run by scripts/build_site.sh before site generation.
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET_DIR = ROOT / "workspace/docs"

# (output file, section title, sources) — a source is a directory of .adoc
# files or a single .adoc file.
SECTIONS = [
    ("20-practice-standards.gen.adoc", "Architecture Practice Standards", [
        ROOT / "docs/architecture-as-code",
        # Governed by Architecture Practice and machine-read by the validator,
        # so it lives with the shared model rather than under docs/.
        ROOT / "models/shared/tags/approved-tags.adoc",
    ]),
    ("21-policies.gen.adoc", "Policies", [ROOT / "docs/policies"]),
    ("22-capabilities.gen.adoc", "Business Capabilities", [ROOT / "docs/capabilities"]),
]

HEADER = "// GENERATED by scripts/aggregate_docs.py from {source} — edit there.\n"


def shift_headings(text: str) -> str:
    """Demote every AsciiDoc heading one level (= Title -> == Title)."""
    lines = []
    for line in text.splitlines():
        if line.startswith("=") and not line.startswith("|==="):
            line = "=" + line
        lines.append(line)
    return "\n".join(lines)


def main() -> None:
    for filename, title, sources in SECTIONS:
        parts = [
            HEADER.format(
                source=", ".join(s.relative_to(ROOT).as_posix() for s in sources)
            ),
            f"== {title}",
            "",
        ]
        for source in sources:
            docs = sorted(source.glob("*.adoc")) if source.is_dir() else [source]
            for doc in docs:
                parts.append(shift_headings(doc.read_text()).rstrip())
                parts.append("")
        target = TARGET_DIR / filename
        target.write_text("\n".join(parts))
        print(f"wrote {target.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
