#!/usr/bin/env python3
"""Generate inventory reports from model properties.

Outputs (AsciiDoc, rendered into the portal as workspace documentation):
  workspaces/Technology/docs/90-technology-inventory.gen.adoc
  workspaces/Integration/docs/90-interface-catalogue.gen.adoc

*.gen.adoc files are generated artifacts and are gitignored.
"""

from __future__ import annotations

from collections import defaultdict
from datetime import date
from pathlib import Path

from dsl_model import ROOT, parse_model

HEADER = "// GENERATED by scripts/generate_reports.py — do not edit.\n"


def grouped_section(title: str, systems, prop: str) -> str:
    groups = defaultdict(list)
    for system in systems:
        groups[system.properties.get(prop) or "(not set)"].append(system.name)
    lines = [f"=== Systems by {title}", ""]
    for value in sorted(groups):
        lines.append(f"* *{value}*: {', '.join(sorted(groups[value]))}")
    lines.append("")
    return "\n".join(lines)


def technology_inventory(model) -> str:
    lines = [
        HEADER,
        "== Technology Inventory (generated)",
        "",
        f"_Generated from model properties on {date.today().isoformat()}._",
        "",
        "=== All Systems",
        "",
        '[cols="2,2,2,2,2,1,1",options="header"]',
        "|===",
        "| System | Capability | Owner | Runtime | Database | Hosting | Criticality",
    ]
    for system in sorted(model.systems, key=lambda s: s.name):
        p = system.properties.get
        lines.append(
            f"| {system.name} | {p('capability', '-')} | {p('owner', '-')} "
            f"| {p('runtime', '-')} | {p('database', '-')} | {p('hosting', '-')} "
            f"| {p('criticality', '-')}"
        )
    lines += ["|===", ""]
    for prop, title in (
        ("runtime", "Runtime"),
        ("database", "Database"),
        ("hosting", "Hosting"),
        ("lifecycle", "Lifecycle"),
        ("criticality", "Criticality"),
        ("capability", "Capability"),
    ):
        lines.append(grouped_section(title, model.systems, prop))
    return "\n".join(lines)


def interface_catalogue(model) -> str:
    element_names = {s.identifier: s.name for s in model.systems}
    system_ids = set(element_names)

    lines = [
        HEADER,
        "== Interface Catalogue (generated)",
        "",
        f"_Generated from integration assets on {date.today().isoformat()}._",
        "",
        '[cols="2,2,3,2",options="header"]',
        "|===",
        "| Source | Target | Description | Technology",
    ]
    for relationship in model.relationships:
        # System-to-system integrations only (the first-class integration assets).
        if relationship.source in system_ids and relationship.destination in system_ids:
            lines.append(
                f"| {element_names[relationship.source]} "
                f"| {element_names[relationship.destination]} "
                f"| {relationship.description} "
                f"| {relationship.technology or '-'}"
            )
    lines += [
        "|===",
        "",
        "Full interface documentation (authentication, classification, ownership, "
        "monitoring) lives in `models/integrations/<Source-Target>/docs/`.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    model = parse_model()
    outputs = {
        ROOT / "workspaces/Technology/docs/90-technology-inventory.gen.adoc":
            technology_inventory(model),
        ROOT / "workspaces/Integration/docs/90-interface-catalogue.gen.adoc":
            interface_catalogue(model),
    }
    for path, content in outputs.items():
        path.write_text(content)
        print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
