#!/usr/bin/env python3
"""Generate the mechanical views so nobody hand-writes them.

At 300 systems, a per-system `views.dsl` plus a matching `!include` line is 600
pieces of identical boilerplate. This generates the standard context view for
every software system, and one landscape per portfolio category, into
`models/shared/views-generated.dsl`.

Hand-written views still win: a system with its own `views.dsl` is skipped here,
so anything needing custom scoping or layout stays under the author's control.

Scale note (measured — see docs/architecture-as-code/scale.adoc): landscape views
degrade catastrophically past ~60 elements, so a category holding more than
that must be split before its landscape is usable.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

from dsl_model import ROOT, parse_model

OUTPUT = ROOT / "models/shared/views-generated.dsl"
SYSTEMS_DIR = ROOT / "models/enterprise/systems"
SOLUTIONS_DIR = ROOT / "models/solutions"

# Above this many elements a landscape stops being readable and starts being
# slow; the spike measured 60 fine, 195 unusable, 300 unrenderable.
LANDSCAPE_WARN_THRESHOLD = 60


def hand_written_context_views() -> set[str]:
    """Identifiers that already have an author-written systemContext view.

    Checked per *view*, not per element: a solution can hand-write its container
    and deployment views and still receive the standard generated context view.
    """
    written = set()
    for views_file in list(ROOT.glob("models/**/views.dsl")) + [
        ROOT / "workspace/workspace.dsl"
    ]:
        if not views_file.exists():
            continue
        for match in re.finditer(r"^\s*systemContext\s+(\w+)", views_file.read_text(), re.M):
            written.add(match.group(1))
    return written


def main() -> int:
    model = parse_model()
    vocabulary = json.loads((ROOT / "models/shared/vocabulary.json").read_text())
    categories = vocabulary["portfolioCategories"]

    lines = [
        "# GENERATED by scripts/generate_views.py — do not edit.",
        "# Standard context views for every system, plus one landscape per",
        "# portfolio category. Elements with their own views.dsl are skipped.",
        "",
    ]

    authored = hand_written_context_views()
    generated = skipped = 0
    for system in sorted(model.systems, key=lambda s: s.name):
        if system.identifier in authored:
            skipped += 1
            continue
        key = system.name.replace(" ", "")
        lines += [
            f'systemContext {system.identifier} "{key}-Context" '
            f'"{system.name} and its direct dependencies." {{',
            "    include *",
            "    autoLayout lr",
            "}",
            "",
        ]
        generated += 1

    # One landscape per portfolio category, scoped by the category tag.
    sizes = {c: sum(1 for s in model.systems if c in s.tags) for c in categories}
    for category in categories:
        key = category.replace(" ", "")
        lines += [
            f'systemLandscape "{key}" "{category} — portfolio landscape." {{',
            f'    include "element.tag=={category}"',
            "    autoLayout lr",
            "}",
            "",
        ]

    OUTPUT.write_text("\n".join(lines))
    print(
        f"wrote {OUTPUT.relative_to(ROOT)}: {generated} context views generated, "
        f"{skipped} hand-written skipped, {len(categories)} category landscapes"
    )

    oversized = {c: n for c, n in sizes.items() if n > LANDSCAPE_WARN_THRESHOLD}
    for category, count in oversized.items():
        print(
            f"  ! '{category}' holds {count} systems — landscapes above "
            f"{LANDSCAPE_WARN_THRESHOLD} become unreadable and slow to render. "
            f"Split it into sub-categories.",
            file=sys.stderr,
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
