#!/usr/bin/env python3
"""Generate inventory reports from model properties.

Outputs (AsciiDoc, rendered into the portal as workspace documentation):
  workspace/docs/90-technology-inventory.gen.adoc
  workspace/docs/91-interface-catalogue.gen.adoc

*.gen.adoc files are generated artifacts and are gitignored.
"""

from __future__ import annotations

import re
from collections import defaultdict
from datetime import date
from pathlib import Path

from dsl_model import ROOT, parse_model

HEADER = "// GENERATED by scripts/generate_reports.py — do not edit.\n"


def grouped_section(title: str, systems, prop: str) -> str:
    groups = defaultdict(list)
    for system in systems:
        groups[system.properties.get(prop) or "(not set)"].append(system.name)
    lines = [f"=== Systems by {title}", ""]
    for value in sorted(groups):
        lines.append(f"* *{value}*: {', '.join(sorted(groups[value]))}")
    lines.append("")
    return "\n".join(lines)


def technology_inventory(model) -> str:
    lines = [
        HEADER,
        "== Technology Inventory (generated)",
        "",
        f"_Generated from model properties on {date.today().isoformat()}._",
        "",
        "=== All Systems",
        "",
        '[cols="2,2,2,2,2,1,1",options="header"]',
        "|===",
        "| System | Capability | Owner | Runtime | Database | Hosting | Criticality",
    ]
    for system in sorted(model.systems, key=lambda s: s.name):
        p = system.properties.get
        lines.append(
            f"| {system.name} | {p('capability', '-')} | {p('owner', '-')} "
            f"| {p('runtime', '-')} | {p('database', '-')} | {p('hosting', '-')} "
            f"| {p('criticality', '-')}"
        )
    lines += ["|===", ""]
    for prop, title in (
        ("runtime", "Runtime"),
        ("database", "Database"),
        ("hosting", "Hosting"),
        ("lifecycle", "Lifecycle"),
        ("criticality", "Criticality"),
        ("capability", "Capability"),
    ):
        lines.append(grouped_section(title, model.systems, prop))
    return "\n".join(lines)


def interface_catalogue(model) -> str:
    element_names = {s.identifier: s.name for s in model.systems}
    system_ids = set(element_names)

    lines = [
        HEADER,
        "== Interface Catalogue (generated)",
        "",
        f"_Generated from integration assets on {date.today().isoformat()}._",
        "",
        '[cols="2,2,3,2",options="header"]',
        "|===",
        "| Source | Target | Description | Technology",
    ]
    for relationship in model.relationships:
        # System-to-system integrations only (the first-class integration assets).
        if relationship.source in system_ids and relationship.destination in system_ids:
            lines.append(
                f"| {element_names[relationship.source]} "
                f"| {element_names[relationship.destination]} "
                f"| {relationship.description} "
                f"| {relationship.technology or '-'}"
            )
    lines += ["|===", ""]
    lines.append(interface_details())
    return "\n".join(lines)


def adr_to_adoc(text: str) -> tuple[str, str]:
    """Render an adr-tools Markdown ADR as (title, AsciiDoc body).

    Section headings become bold labels rather than nested headings: these are
    already deep inside the catalogue, and AsciiDoc has no level beyond
    '======'.
    """
    title = ""
    out = []
    for line in text.splitlines():
        if line.startswith("# ") and not title:
            # "1. Use event streaming ..." -> "Use event streaming ..."
            title = re.sub(r"^\d+\.\s*", "", line[2:].strip())
        elif line.startswith("## "):
            out += ["", f"*{line[3:].strip()}*", ""]
        else:
            out.append(line)
    body = re.sub(r"\n{3,}", "\n\n", "\n".join(out)).strip()
    return title, body


def shift_headings(text: str, levels: int) -> str:
    """Demote every AsciiDoc heading by `levels` (== Title -> ==== Title)."""
    return "\n".join(
        "=" * levels + line
        if line.startswith("=") and not line.startswith("|===")
        else line
        for line in text.splitlines()
    )


def interface_details() -> str:
    """Inline each integration's interface documentation and ADRs.

    Structurizr attaches documentation to elements, and integrations are
    relationships — so `!docs` cannot reach these files. Publishing them here
    keeps the authored content (authentication, classification, ownership,
    monitoring) visible in the portal while it stays owned by the integration
    asset folder.
    """
    integrations_dir = ROOT / "models/integrations"
    lines = ["=== Interface Documentation", ""]

    for folder in sorted(p for p in integrations_dir.iterdir() if p.is_dir()):
        doc = folder / "docs" / "interface.adoc"
        if not doc.exists():
            continue

        # The doc's own "== Interface: A -> B" becomes "====", sitting under
        # this section; its inner headings follow at "=====".
        lines += [shift_headings(doc.read_text().strip(), 2), ""]

        adr_dir = folder / "adr"
        if adr_dir.is_dir():
            for adr in sorted(adr_dir.glob("*.md")):
                title, body = adr_to_adoc(adr.read_text().strip())
                lines += [f"===== Decision: {title}", "", body, ""]

        lines.append(f"_Source: `models/integrations/{folder.name}/`_")
        lines += ["", "'''", ""]

    return "\n".join(lines)


def main() -> None:
    model = parse_model()
    outputs = {
        ROOT / "workspace/docs/90-technology-inventory.gen.adoc":
            technology_inventory(model),
        ROOT / "workspace/docs/91-interface-catalogue.gen.adoc":
            interface_catalogue(model),
    }
    for path, content in outputs.items():
        path.write_text(content)
        print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
